# GitHub Actions: Secrets, Variables, and Environment Protection
# This workflow demonstrates managing secrets, variables, and environment-specific configurations
# Key concepts: repo/org/environment secrets, variables, environment protection rules

name: 07 - Secrets & Variables

on:
  push:
    branches: [main]
  workflow_dispatch:

# Workflow-level environment variables
env:
  GLOBAL_ENV_VAR: "Available to all jobs"
  LOG_LEVEL: "info"

jobs:
  # Job 1: Using repository secrets
  repository-secrets:
    name: Repository Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use repository secret
        run: |
          echo "Repository secret exists: ${{ secrets.GITHUB_TOKEN != '' }}"
          # Never print actual secret values!
          echo "Secret length: ${#GITHUB_TOKEN}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Example of using custom secrets (would need to be configured in repo settings)
      - name: Use custom secrets (example)
        if: false  # Disabled - requires actual secrets to be configured
        run: |
          echo "API Key exists: ${{ secrets.API_KEY != '' }}"
          echo "Database URL exists: ${{ secrets.DATABASE_URL != '' }}"
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  # Job 2: Using repository variables
  repository-variables:
    name: Repository Variables
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use repository variables
        run: |
          echo "Global env var: $GLOBAL_ENV_VAR"
          echo "Log level: $LOG_LEVEL"
        env:
          GLOBAL_ENV_VAR: ${{ env.GLOBAL_ENV_VAR }}
          LOG_LEVEL: ${{ env.LOG_LEVEL }}

      # Example of using custom variables (would need to be configured in repo settings)
      - name: Use custom variables (example)
        if: false  # Disabled - requires actual variables to be configured
        run: |
          echo "App name: ${{ vars.APP_NAME }}"
          echo "Environment: ${{ vars.ENVIRONMENT }}"

  # Job 3: Job-level environment variables
  job-level-env:
    name: Job-Level Environment
    runs-on: ubuntu-latest
    env:
      JOB_ENV_VAR: "Only available in this job"
      BUILD_TYPE: "production"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print job environment
        run: |
          echo "Job env var: $JOB_ENV_VAR"
          echo "Build type: $BUILD_TYPE"
          echo "Global env var: $GLOBAL_ENV_VAR"

  # Job 4: Step-level environment variables
  step-level-env:
    name: Step-Level Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Step with custom environment
        env:
          STEP_ENV_VAR: "Only in this step"
          API_ENDPOINT: "https://api.example.com"
        run: |
          echo "Step env var: $STEP_ENV_VAR"
          echo "API endpoint: $API_ENDPOINT"

  # Job 5: Conditional environment access
  conditional-env:
    name: Conditional Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment based on branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          fi

      - name: Use dynamic environment
        run: |
          echo "Environment: $ENVIRONMENT"

  # Job 6: Environment-specific deployment (example)
  environment-deployment:
    name: Deploy to ${{ matrix.environment }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [staging, production]
    # This would require environment protection rules to be configured
    environment:
      name: ${{ matrix.environment }}
      url: https://${{ matrix.environment }}.example.com
    if: false  # Disabled - requires environment configuration
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to ${{ matrix.environment }}
        run: |
          echo "Deploying to ${{ matrix.environment }}"
          echo "Environment URL: https://${{ matrix.environment }}.example.com"

  # Job 7: Masking sensitive values
  masking-secrets:
    name: Masking Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add mask for sensitive value
        run: |
          # Mask a sensitive value in logs
          echo "::add-mask::my-secret-value"
          echo "This value will be masked: my-secret-value"

      - name: Use masked secret
        run: |
          SECRET_VALUE="${{ secrets.GITHUB_TOKEN }}"
          echo "Secret is automatically masked by GitHub"

  # Job 8: Secret rotation and best practices
  secret-best-practices:
    name: Secret Best Practices
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Best practices for secrets
        run: |
          echo "=== Secret Best Practices ==="
          echo "1. Never log secrets"
          echo "2. Use environment-specific secrets"
          echo "3. Rotate secrets regularly"
          echo "4. Use least privilege principle"
          echo "5. Use GitHub's secret scanning"
          echo "6. Use environment protection rules"
          echo "7. Audit secret access"

  # Job 9: Using secrets in action inputs
  secrets-in-actions:
    name: Secrets in Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Example: Using secret in action input
      - name: Deploy with secret (example)
        if: false  # Disabled - requires actual setup
        uses: actions/upload-artifact@v3
        with:
          name: deployment-artifact
          path: dist/

  # Job 10: Context variables reference
  context-variables:
    name: Context Variables
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print context variables
        run: |
          echo "=== GitHub Context ==="
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Event: ${{ github.event_name }}"
          echo "Workspace: ${{ github.workspace }}"

# Secrets & Variables Reference:
# Repository Secrets:
#   - Configured in repo settings
#   - Encrypted and not visible in logs
#   - Access: ${{ secrets.SECRET_NAME }}
#
# Organization Secrets:
#   - Shared across multiple repositories
#   - Configured in org settings
#   - Can be limited to specific repos
#
# Environment Secrets:
#   - Specific to deployment environments
#   - Override repo/org secrets
#   - Require environment protection rules
#
# Repository Variables:
#   - Non-sensitive configuration
#   - Visible in logs
#   - Access: ${{ vars.VARIABLE_NAME }}
#
# Environment Variables:
#   - Workflow-level: Available to all jobs
#   - Job-level: Available to all steps in job
#   - Step-level: Available only to that step
#
# Best Practices:
#   1. Use secrets for sensitive data (API keys, tokens, passwords)
#   2. Use variables for non-sensitive configuration
#   3. Never log secrets
#   4. Use environment protection rules for production
#   5. Rotate secrets regularly
#   6. Use least privilege principle
#   7. Audit secret access
#   8. Use GitHub's secret scanning
#
# Environment Protection Rules:
#   - Require reviews before deployment
#   - Restrict deployment branches
#   - Require status checks to pass
#   - Require dismissal of stale reviews
